### ISSUE TITLE
specificity of input[type="search"] box-sizing

### ISSUE THREAD

**Issue by nikvm** [inuitcss/generic.normalize#8]
I was styling a search field today and relied on it being set to `box-sizing: border-box`.
I noticed that [`input[type="search"]`](https://github.com/inuitcss/generic.normalize/blob/master/_generic.normalize.scss#L356-L359) `box-sizing` rule trumps the generic rules in [inuit-box-sizing](https://github.com/inuitcss/generic.box-sizing/blob/master/_generic.box-sizing.scss#L11).
I ended up setting the rule in my component class, which is all right but not expected.

Any thoughts? - Thanks.

**Comment by csshugs** [comment]
@nikvm It seems, this wont be "fixed" in the [original repo](https://github.com/necolas/normalize.css), as discussed [here](https://github.com/necolas/normalize.css/issues/471) which is a shame I think. I've gone through this issue too, having to override it myself with `border-box`. Due to the fact that this is just a copy of the official normalize.css, we need to live with it.

Though I think this is something we need to override ourselves in every project and could probably go into something like `_reset.scss` in the base layer, e.g.
```scss
input[type="search"] {
    box-sizing: border-box;
}
```

**Comment by necolas** [comment]
I'd merge a patch for this normalize issue; agree that it's annoying / wrong.

**Comment by csshugs** [comment]
Ah that's great news and a big relief. Thanks @necolas for addressing this issue!

**Comment by csshugs** [comment]
Just for the records: The above mentioned patch is being [applied](https://github.com/necolas/normalize.css/pull/496#event-522242867)

**Comment by csshugs** [comment]
For the records again: [Version 4.0.0 of normalize.css has landed](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#400-march-19-2016). In that version, this issue is being addressed:

> Remove unnecessary box-sizing for input[type="search"] in Chrome, Edge, Firefox, IE, and Safari

With #10, there is already a PR to update to version 4.0.0. When #10 is merged, this issue can be closed.

**Comment by csshugs** [comment]
@nikvm or @anselmh :
#10 is merged. Can you close this issue?

**Comment by csshugs** [comment]
👍
